// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHhchF7nxqJU11ztb02kr1c5C0Lezsr5o',
    appId: '1:959678277419:web:d3fccebdfcfcb7ca07476e',
    messagingSenderId: '959678277419',
    projectId: 'my-whatsapp-df80f',
    authDomain: 'my-whatsapp-df80f.firebaseapp.com',
    storageBucket: 'my-whatsapp-df80f.appspot.com',
    measurementId: 'G-2VFLKTGSPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7R7_JMYoYnHxf16KJNxEv6rU4TnXS2ak',
    appId: '1:959678277419:android:5385843b232ef49107476e',
    messagingSenderId: '959678277419',
    projectId: 'my-whatsapp-df80f',
    storageBucket: 'my-whatsapp-df80f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8RiBBEpHrZE3iBrF22TREYaMeTB5Y8Y',
    appId: '1:959678277419:ios:fd052960f9f5782b07476e',
    messagingSenderId: '959678277419',
    projectId: 'my-whatsapp-df80f',
    storageBucket: 'my-whatsapp-df80f.appspot.com',
    iosBundleId: 'com.example.myWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw8RiBBEpHrZE3iBrF22TREYaMeTB5Y8Y',
    appId: '1:959678277419:ios:7e8c9c5e1add1e6407476e',
    messagingSenderId: '959678277419',
    projectId: 'my-whatsapp-df80f',
    storageBucket: 'my-whatsapp-df80f.appspot.com',
    iosBundleId: 'com.example.myWhatsapp.RunnerTests',
  );
}
